---
title: "Time series"
author: "陳映均"
date: "2023-04-11"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 載入package

```{r,warning = FALSE,message=FALSE}
library(ggplot2);library(reshape2);library(zoo);library(FinTS);library(e1071);library(fBasics);library(pander);library("openxlsx");library(PerformanceAnalytics);library(quantmod);library(dygraphs) ;

```
# 讀取資料

```{r}
data_original <- read.csv("./data.csv")

ggplot(data_original,aes(x = X,y=x
))+geom_line()+labs(x = "X", 
y = "x",title = "Original Data")
ggsave("data_original.png")

data <-data_original[1:991,]
```

```{r}
sum(is.na(data))
# 確認無缺失值

#計算simple retrun
data_simple_return <- diff(data$x) / data$x[- length(data$x)] 

#計算log return
data_log_return <- diff(log(data$x))

data1 <- data[-1,]
data_simple.index <- data1$X
data_simple.data <- data_simple_return
data_simple <- zoo(data_simple.data,data_simple.index)

data_log.index <- data1$X
data_log.data <- data_log_return
data_log <- zoo(data_log.data,data_log.index)

ggplot(data_simple,aes(x = data_simple.index,y=data_simple.data
))+geom_line()+ geom_smooth(method = "lm", se = FALSE)+labs(x = "x", y = "Simple return",title = "Data simple return")

ggsave("data_simple.png")

ggplot(data_log,aes(x = data_log.index,y=data_log.data
))+geom_line()+geom_smooth(method = "lm", se = FALSE)+labs(x = "x", 
y = "Log return",title = "Data log return")
ggsave("data_log.png")
```
```{r}
log.returns <- FinTS.stats(data_log)
pander::pander(log.returns)

```

```{r}
#檢驗是否是stationary
library(tseries)

adf.test(data$x)
#the original data is  not stationary.
adf.test(data_simple)
#the simple return is stationary.
adf.test(data_log)
#the log return is stationary.
```

```{r}
#install.packages('TSA')
library(TSA)
acf=acf(data_log)
pacf_=pacf(data_log) 
#The PACF shown in Figure above is suggestive of an AR(2) model
eacf(data_log)
#Candidate models from EACF plot are {ARIMA(1,0,2), ARIMA(2,0,1), ARIMA(2,0,2)}
```
```{r}
#install.packages("forecast")
library(forecast)
mod <- auto.arima(data_log,seasonal=FALSE,
                  test = 'adf' , ic='aic')
mod
#基於AIC以及ADF，p= 3, d = 0, q = 1
```


```{R}
library(lmtest)

model_102_css = arima(data_log,order=c(1,0,2),method='CSS')
coeftest(model_102_css)
# intercept insignificant

model_102_ML = arima(data_log,order=c(1,0,2),method='ML')
coeftest(model_102_ML)
# intercept insignificant

#重新modeling
model_102_ML_new = arima(data_log, order=c(1,0,2),fixed=c(NA,NA,NA,0),method="ML")
#Coefficients:
#         ar1     ma1      ma2  intercept
#      0.8635  0.1312  -0.0991          0
#s.e.  0.0216  0.0384   0.0398          0

#sigma^2 estimated as 3.316e-07:  log likelihood = 5979.6,  aic = -11953.21

model_202_css = arima(data_log,order=c(2,0,2),method='CSS')
coeftest(model_202_css)
#ma(2)、intercept insignificant

model_202_ML = arima(data_log,order=c(2,0,2),method='ML')
coeftest(model_202_ML) 
#ma(2)、intercept insignificant

model_201_css = arima(data_log,order=c(2,0,1),method='CSS')
coeftest(model_201_css)
# intercept insignificant

model_201_ML = arima(data_log,order=c(2,0,1),method='ML')
coeftest(model_201_ML)
# intercept insignificant

#重新modeling
model_201_ML_new = arima(data_log, order=c(2,0,1),fixed=c(NA,NA,NA,0),method="ML")
coeftest(model_201_ML_new)
#Coefficients:
#         ar1     ar2     ma1  intercept
#      0.2581  0.5064  0.7348          0
#s.e.  0.0877  0.0805  0.0742          0

#sigma^2 estimated as 3.297e-07:  log likelihood = 5982.47,  aic = -11958.93
model_301_css = arima(data_log,order=c(3,0,1),method='CSS')
coeftest(model_301_css)
# ar3、intercept insignificant
model_301_ML = arima(data_log,order=c(3,0,1),method='ML')
coeftest(model_301_ML)
# ar3、intercept insignificant

model_302_css = arima(data_log,order=c(3,0,2),method='CSS')
coeftest(model_302_css)
# ar1、ar3、ma1、ma2 intercept insignificant

sort.score <- function(x, score = c("bic", "aic")){
  if (score == "aic"){
    x[with(x, order(AIC)),]
    
  } else if (score == "bic") {
    x[with(x, order(BIC)),]
    
  } else {
    warning('score = "x" only accepts valid arguments ("aic","bic")')
  }
}


sort.score(AIC(model_102_ML_new,model_201_ML_new), score = "aic")
#                 df       AIC
#model_201_ML_new  4 -11956.93
#model_102_ML_new  4 -11951.21
sort.score(BIC(model_102_ML_new,model_201_ML_new), score = "bic")
#                 df       BIC
#model_201_ML_new  4 -11937.34
#model_102_ML_new  4 -11931.62

# choose ARIMA(2,0,1) model
```


```{r}
model_201_ML_new 
#Coefficients:
#         ar1     ar2     ma1  intercept
#      0.2581  0.5064  0.7348          0
#s.e.  0.0877  0.0805  0.0742          0

#sigma^2 estimated as 3.297e-07:  log likelihood = 5982.47,  aic = -11958.93


```

```{r}
model_exactML <-arima0(data_log,order=c(2,0,1),method='ML',delta = -1)
#Coefficients:
#         ar1     ar2     ma1  intercept
#      0.2576  0.5040  0.7343     -1e-04
#s.e.  0.0290  0.0801  0.1601      1e-04

#sigma^2 estimated as 3.293e-07:  log #likelihood = 5983.08,  aic = -11956.17
n <- length(data_log)
eps <-rep(1,n)
eps[1:2] <- rep(0,2)
  for (i in 3:n) {
    eps[i] <- data_log[i] - (model_exactML$coef[1]*as.numeric(data_log[i-1])) - (model_exactML$coef[2]*as.numeric(data_log[i-2])) - (model_exactML$coef[3]*eps[i-1])
  }

cbind(error=eps[1:10],residuals=model_exactML$residuals[1:10])
```

```{r}
#install.packages("forecast")
library(forecast)
library(TSA)
residuals <- residuals(model_exactML)
acf=acf(residuals)
pacf_=pacf(residuals)

Box.test(residuals)
#p-value = 0.949>0.05，white noise

checkresiduals(residuals)
#data:  Residuals
#Q* = 0.99258, df = 10, p-value = 0.9998
# Not reject HO，The residuals are independently distributed.
jarque.bera.test(residuals)
#p-value = 0.9602 >0.05，We would not be able to reject the null hypothesis that the data is normally distributed

```

```{r}
#計算log return
last_10_log_returns <- tail(diff(log(data_original$x)),10)

forecasts <- predict(model_exactML, n.ahead = 10)

predicted_values <- forecasts$pred
lower_ci <- predicted_values - 1.96 * forecasts$se
upper_ci <- predicted_values + 1.96 * forecasts$se

# Create a time series plot of the last 10 log returns and the predicted values with the 95% confidence interval
ymin <- min(last_10_log_returns, lower_ci)
ymax <- max(last_10_log_returns, upper_ci)

# Create a time series plot of the last 10 log returns and the predicted values with the 95% confidence interval
plot(last_10_log_returns, type = "o", col = "blue", ylim = c(ymin, ymax), xlab = "Time", ylab = "Log Returns")
lines(as.numeric(predicted_values), type = "o", col = "red")
lines(as.numeric(lower_ci), col = "green", lty = 2)
lines(as.numeric(upper_ci), col = "green", lty = 2)
legend("topleft", legend = c("Last 10 Log Returns", "Predicted Values", "95% CI"), col = c("blue", "red", "green"), lty = c(1, 1, 2), cex = 0.8)
```